import { Injectable } from "@nestjs/common";
import { SupabaseService } from "../supabase/supabase.service";

@Injectable()
export class CustomersService {
  constructor(private supabase: SupabaseService) {}

  async findAll() {
    const { data, error } = await this.supabase
      .getClient()
      .from("customers")
      .select("*")
      .order("id");
    if (error) throw error;
    return data;
  }

  async search(query: string) {
    const { data, error } = await this.supabase
      .getClient()
      .from("customers")
      .select("*")
      .or(`name.ilike.%${query}%,customer_code.ilike.%${query}%,phone.ilike.%${query}%`)
      .order("name")
      .limit(20);
    if (error) throw error;
    return data;
  }

  async findOrCreate(name: string, phone?: string) {
    // If phone provided, try to find by phone first
    if (phone) {
      const { data: existing } = await this.supabase
        .getClient()
        .from("customers")
        .select("*")
        .eq("phone", phone)
        .single();

      if (existing) {
        const newCount = existing.visit_count + 1;
        const resetCount = newCount % 5 === 0 ? 0 : newCount;
        await this.supabase
          .getClient()
          .from("customers")
          .update({ visit_count: resetCount })
          .eq("id", existing.id);
        return { ...existing, visit_count: resetCount };
      }
    }

    // Create new customer (customer_code auto-generated by trigger)
    const { data, error } = await this.supabase
      .getClient()
      .from("customers")
      .insert({ name, phone: phone || "", visit_count: 1 })
      .select()
      .single();
    if (error) throw error;
    return data;
  }

  async incrementVisit(customerId: number) {
    const { data: customer } = await this.supabase
      .getClient()
      .from("customers")
      .select("*")
      .eq("id", customerId)
      .single();

    if (!customer) throw new Error("Customer not found");

    const newCount = customer.visit_count + 1;
    const resetCount = newCount % 5 === 0 ? 0 : newCount;

    const { data, error } = await this.supabase
      .getClient()
      .from("customers")
      .update({ visit_count: resetCount })
      .eq("id", customerId)
      .select()
      .single();
    if (error) throw error;
    return { ...data, free_visit: newCount % 5 === 0 };
  }
}
